src/website/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views.generic import RedirectView

admin.autodiscover()


def protected_render(request, *args, **kwargs):
    valid_request = False
    if request.user.is_authenticated():
        valid_request = True
    if not valid_request:
        raise Http404
    return render(request, *args, **kwargs)


development_urlpatterns = patterns('',

    # Development static design templates
    url(r'^d/my-dashboard/$', protected_render, {'template_name': 'dev/dashboard.html'}),
    url(r'^d/local-dashboard/$', protected_render, {'template_name': 'dev/local-dashboard.html'}),
    url(r'^d/video-stream/$', protected_render, {'template_name': 'dev/video.html'}),
    url(r'^d/meet-the-team/$', protected_render, {'template_name': 'dev/meet-the-team.html'}),
    url(r'^d/meet-the-team-member/$', protected_render, {'template_name': 'dev/team.html'}),
    url(r'^d/local-mind/$', protected_render, {'template_name': 'dev/lm.html'}),
    url(r'^d/events-diary/$', protected_render, {'template_name': 'dev/event-diary.html'}),
    url(r'^d/my-local-area/$', protected_render, {'template_name': 'dev/local-map.html'}),
    url(r'^d/funding-map/$', protected_render, {'template_name': 'dev/funding-map.html'}),
    url(r'^d/todos/$', protected_render, {'template_name': 'dev/task.html'}),
    url(r'^d/call-out/$', protected_render, {'template_name': 'dev/questions-and-answers.html'}),
    url(r'^d/engine-room/$', protected_render, {'template_name': 'dev/documents.html'}),
    url(r'^d/external-news/$', protected_render, {'template_name': 'dev/external-news.html'}),
    url(r'^d/positive-news/$', protected_render, {'template_name': 'dev/positive-news.html'}),
    url(r'^d/brand/$', protected_render, {'template_name': 'dev/brand.html'}),
    url(r'^d/the-net-works/$', protected_render, {'template_name': 'dev/the-net-works.html'}),
    url(r'^d/openhub-updates/$', protected_render, {'template_name': 'dev/openhub-updates.html'}),
    url(r'^d/national-mind-updates/$', protected_render, {'template_name': 'dev/national-mind-updates.html'}),
    url(r'^d/buddy-search/$', protected_render, {'template_name': 'dev/buddy-search.html'}),
    url(r'^d/hot-topic-news/$', protected_render, {'template_name': 'dev/hot-topic-news.html'}),
    url(r'^d/engine-room-2/$', protected_render, {'template_name': 'dev/engine-room.html'}),
    url(r'^d/404/$', protected_render, {'template_name': 'dev/404.html'}),
    url(r'^d/mqm/$', protected_render, {'template_name': 'dev/mqm.html'}),


    url(r'^sign-up/part1$', protected_render, {'template_name': 'dev/signup/part1.html'}),
    url(r'^sign-up/part2$', protected_render, {'template_name': 'dev/signup/part2.html'}),
    url(r'^sign-up/part3$', protected_render, {'template_name': 'dev/signup/part3.html'}),
    url(r'^sign-up/part4$', protected_render, {'template_name': 'dev/signup/part4.html'}),
    url(r'^sign-up/part5$', protected_render, {'template_name': 'dev/signup/part5.html'}),
    url(r'^sign-up/part6$', protected_render, {'template_name': 'dev/signup/part6.html'}),

    #modals
    #url(r'^_addClinicalResearch/$', protected_render, {'template_name': 'dev/modals/add-clinical-research.html'}),
    #url(r'^_addExternalNews/$', protected_render, {'template_name': 'dev/modals/add-external-news.html'}),
    url(r'^_addPositiveNews/$', protected_render, {'template_name': 'dev/modals/add-positive-news.html'}),
    url(r'^_addService/$', protected_render, {'template_name': 'dev/modals/add-service.html'}),
    url(r'^_addEvent/$', protected_render, {'template_name': 'dev/modals/add-event.html'}),
    url(r'^_addKeyPartner/$', protected_render, {'template_name': 'dev/modals/add-key-partner.html'}),
    url(r'^_addFunding/$', protected_render, {'template_name': 'dev/modals/add-funding.html'}),
    url(r'^_addTodo/$', protected_render, {'template_name': 'dev/modals/add-todo.html'}),
    url(r'^_addQuestion/$', protected_render, {'template_name': 'dev/modals/add-question.html'}),
    url(r'^_addDocument/$', protected_render, {'template_name': 'dev/modals/add-document.html'}),
    url(r'^_addNews/$', protected_render, {'template_name': 'dev/modals/add-news.html'}),
    url(r'^_addVideo/$', protected_render, {'template_name': 'dev/modals/add-video.html'}),
    url(r'^_addPassword/$', protected_render, {'template_name': 'dev/modals/change-password.html'}),
    url(r'^_addResource/$', protected_render, {'template_name': 'dev/modals/add-resource.html'}),
    url(r'^_addAnswer/$', protected_render, {'template_name': 'dev/modals/add-answer.html'}),


    #calendar widget urls
    url(r'^calendarTemplates/day.html$', protected_render, {'template_name': 'calendarTemplates/day.html'}),
    url(r'^calendarTemplates/events-list.html$', protected_render, {'template_name': 'calendarTemplates/events-list.html'}),
    url(r'^calendarTemplates/modal.html$', protected_render, {'template_name': 'calendarTemplates/modal.html'}),
    url(r'^calendarTemplates/month-day.html$', protected_render, {'template_name': 'calendarTemplates/month-day.html'}),
    url(r'^calendarTemplates/month.html$', protected_render, {'template_name': 'calendarTemplates/month.html'}),
    url(r'^calendarTemplates/week-days.html$', protected_render, {'template_name': 'calendarTemplates/week-days.html'}),
    url(r'^calendarTemplates/week.html$', protected_render, {'template_name': 'calendarTemplates/week.html'}),
    url(r'^calendarTemplates/year-month.html$', protected_render, {'template_name': 'calendarTemplates/year-month.html'}),
    url(r'^calendarTemplates/year.html$', protected_render, {'template_name': 'calendarTemplates/year.html'}),
    #

    #general
     url(r'^log-in/$', protected_render, {'template_name': 'dev/login.html'}),
     url(r'^invitee/$', protected_render, {'template_name': 'dev/invitee.html'})
)

urlpatterns = patterns('',
    url(r'^robots.txt$', 'django.shortcuts.render', {'template': 'robots.txt'},),
    url(r'^humans.txt$', 'django.shortcuts.render', {'template': 'humans.txt'},),

    url(r'^api/events/(?P<limit>own|local|national)/$', 'website.diary.views.event_api_list', name='api-events'),
    url(r'^api/events/dates/$', 'website.diary.views.event_api_current_dates', name='api-events-dates'),
    url(r'^api/events/$', 'website.diary.views.event_api_list', name='api-events'),

    url(r'^$', 'website.views.index', name='index'),
    url(r'^signup/profile/(?P<uidb36>[^-/]+)-(?P<token>[^/]+)/$', 'website.accounts.registration.views.signup_profile', name='signup-profile'),
    url(r'^signup/(?P<uidb36>[^-/]+)-(?P<token>[^/]+)/$', 'website.accounts.registration.views.signup_wizard', name='signup'),
    url(r'^signup/(?P<uidb36>[^-/]+)-(?P<token>[^/]+)/(?P<step>[^/]+)/$', 'website.accounts.registration.views.signup_wizard', name='signup'),
    url(r'^api/', include('website.api.urls')),

    # PRODUCTION ready for Workshop 1 -- GREGOR TO COMPLETE THESE
    url(r'^dashboard/$', 'website.accounts.dashboard.views.local_dashboard', name='local-dashboard'),
    url(r'^my-dashboard/$', 'website.accounts.dashboard.views.dashboard', name='dashboard'),
    url(r'^my-dashboard/local-mind/$', 'website.accounts.dashboard.views.local_mind_form', name='local-mind-form'),
    url(r'^my-dashboard/profile/$', 'website.accounts.dashboard.views.profile_form', name='profile-form'),
    url(r'^my-dashboard/invite/$', 'website.accounts.dashboard.views.invite_form', name='invite-form'),
    url(r'^my-dashboard/change-password/$', 'website.accounts.dashboard.views.change_password', name='change-password'),
    url(r'^my-local-area/$', 'website.local_map.views.map_list', name='local-map'),
    url(r'^my-local-area/add/$', 'website.local_map.views.map_list', {'show_form': True}, name='local-map-add'),
    url(r'^positive-news/$', 'website.news.views.positive_news_list', name='positive-news'),
    url(r'^positive-news/add/$', 'website.news.views.positive_news_list', {'show_form': True},  name='positive-news-add'),
    url(r'^positive-news/(?P<slug>[^/]+)/$', 'website.news.views.positive_news_detail', name='positive-news'),

    # ANGELO
    url(r'^external-news/$', 'website.news.views.external_news_list', name='external-news'),
    url(r'^external-news/(?P<slug>[^/]+)/$', 'website.news.views.external_news_detail', name='external-news'),
    url(r'^mind-updates/$', 'website.updates.views.update_list', name='mind-updates'),
    url(r'^mind-updates/(?P<slug>[^/]+)/$', 'website.updates.views.update_detail', name='mind-updates'),
    url(r'^openhub-updates/$', 'website.updates.views.openhub_update_list', name='hub-updates'),
    #url(r'^hub-updates/(?P<slug>[^/]+)/$', 'website.updates.views.openhub_update_detail', name='hub-updates'),

    url(r'^call-out/$', 'website.faq.views.question_list', name='questions'),
    url(r'^call-out/add/$', 'website.faq.views.question_list', {'show_form': True}, name='questions'),
    url(r'^call-out/(?P<pk>\d+)/$', 'website.faq.views.question_detail', name='questions'),
    url(r'^call-out/(?P<pk>\d+)/add-answer/$', 'website.faq.views.question_detail', {'show_form': True}, name='questions-add-answer'),
    url(r'^meet-the-team/$', 'website.local_minds.views.team_detail', name='team'),
    url(r'^meet-the-team/(?P<slug>[^/]+)/$', 'website.local_minds.views.team_detail', name='team'),
    url(r'^meet-the-team/(?P<local_mind_slug>[^/]+)/(?P<slug>[^/]+)/$', 'website.local_minds.views.user_detail', name='team'),
    url(r'^local-mind/(?P<slug>[^/]+)/$', 'website.local_minds.views.local_mind_detail', name='local-mind'),
    url(r'^todos/$', 'website.tasks.views.task_list', name='tasks'),
    url(r'^todos/add/$', 'website.tasks.views.task_list', {'show_form': True}, name='tasks-add'),

src/website/documents/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
import os
import uuid

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import (
    AutoSlugField, CreationDateTimeField, ModificationDateTimeField)
from mediastore.fields import MediaField
from taggit.managers import TaggableManager

from ..privacy.models import PrivacyMixin


def category_count():
    return Category.objects.count()


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    list_image = MediaField(
        related_name='document_category_image',
        limit_choices_to={'content_type__model': 'image'},null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    sort_value = models.IntegerField(default=category_count, db_index=True)

    class Meta:
        ordering = ('sort_value',)
        verbose_name = _(u'Category')
        verbose_name_plural = _(u'Categories')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('documents') + '?category=' + self.slug


def upload_path(instance, filename):
    now = datetime.utcnow()
    name, file_extension = os.path.splitext(filename)
    return os.path.join(
        'documents',
        now.strftime('%Y'),
        now.strftime('%m'),
        now.strftime('%d'),
        '{}{}'.format(uuid.uuid4(), file_extension))


class Document(PrivacyMixin, models.Model):
    local_mind = models.ForeignKey('local_minds.LocalMind', related_name='documents')
    user = models.ForeignKey('accounts.User', related_name='documents')

    title = models.CharField(_('Title'), max_length=250)
    slug = AutoSlugField(populate_from=('title',), unique=True)

    file = models.FileField(_('File'), null=True, blank=True, upload_to=upload_path)
    file_type = models.CharField(max_length=20, null=True, blank=True)

    url = models.URLField(_('URL'), null=True, blank=True, help_text=_(
        'to share if coming from google docs/dropbox - permission will be needed to open'))

    download_count = models.PositiveIntegerField(default=0)

    # categorization
    categories = models.ManyToManyField(Category, verbose_name=_('Categories'),
                                        blank=True, related_name='documents')
    tags = TaggableManager(blank=True)

    created = CreationDateTimeField()
    modified = ModificationDateTimeField()

    class Meta:
        verbose_name = _(u'Document')
        verbose_name_plural = _(u'Documents')
        ordering = ('-created',)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return 'documents', (self.slug,), {}

    def get_download_url(self):
        if self.file:
            return self.file.url
        return self.url

    def save(self, *args, **kwargs):
        if self.file:
            __, extension = os.path.splitext(self.file.name)
            self.file_type = extension.lower().lstrip('.')
        else:
            self.file_type = None
        return super(Document, self).save(*args, **kwargs)

src/website/documents/forms.py
# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _
import floppyforms.__future__ as forms

from ..common.forms import NodeForm
from .models import Document


class DocumentForm(NodeForm):
    class Meta:
        model = Document
        fields = (
            'title',
            'file',
            'url',
            'categories',
            'tags',
            'privacy',
        )

    def clean_url(self):
        file = self.cleaned_data.get('file')
        url = self.cleaned_data.get('url')
        if not file and not url:
            raise forms.ValidationError(
                _('You need to provide at least a file or a url.'))
        return url

src/website/documents/views.py
# -*- coding: utf-8 -*-
import floppyforms.__future__ as forms
from django.core.urlresolvers import reverse
from django.db.models import Count, Max, F
from django.http import HttpResponseRedirect
from django.views.generic import DetailView
from website.views.generic import CommonViewMixin, CommonPrivacyViewMixin, ListCreateView
from ..local_minds.models import LocalMind
from .forms import DocumentForm
from .models import Document, Category


class DocumentSearchForm(forms.Form):
    REGION_CHOICES = (
        ('', 'National',),
    ) + LocalMind.REGION_CHOICES
    region = forms.ChoiceField(choices=REGION_CHOICES, required=False)
    category = forms.ModelChoiceField(
        queryset=Category.objects.order_by('name'),
        to_field_name='slug',
        empty_label=None,
        required=True)

    def filter_queryset(self, queryset):
        if self.is_valid():
            region = self.cleaned_data.get('region')
            if region:
                queryset = queryset.filter(local_mind__region=region)
            category = self.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(categories=category)
        return queryset


category_queryset = Category.objects.order_by('name')
category_queryset = category_queryset.annotate(document_count=Count('documents'))
category_queryset = category_queryset.annotate(download_count=Count('documents__download_count'))
category_queryset = category_queryset.annotate(latest_upload_date=Max('documents__created'))


class CategoryListView(CommonViewMixin, ListCreateView):
    form_class = DocumentForm
    queryset = category_queryset

    def get_success_url(self):
        return self.request.path


category_list = CategoryListView.as_view()


class DocumentListView(CommonPrivacyViewMixin, ListCreateView):
    form_class = DocumentForm
    category_queryset = category_queryset
    queryset = Document.objects.order_by('-created')

    def dispatch(self, request, *args, **kwargs):
        self.search_form = DocumentSearchForm(request.GET)
        if not self.search_form.is_valid():
            return HttpResponseRedirect(reverse('documents-categories'))
        self.category = self.search_form.cleaned_data['category']
        return super(DocumentListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(DocumentListView, self).get_queryset()
        queryset = self.search_form.filter_queryset(queryset)
        return queryset

    def get_form_kwargs(self):
        kwargs = super(DocumentListView, self).get_form_kwargs()
        if self.category:
            kwargs.setdefault('initial', {}).update({'categories': [self.category.pk]})
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs['regions'] = LocalMind.REGION_CHOICES
        kwargs['category'] = self.category
        kwargs['category_list'] = self.category_queryset
        kwargs['search_form'] = self.search_form
        return super(DocumentListView, self).get_context_data(**kwargs)

    def get_success_url(self):
        return self.request.path


document_list = DocumentListView.as_view()


class DocumentDetailView(CommonPrivacyViewMixin, DetailView):
    category_queryset = category_queryset
    queryset = Document.objects.order_by('-created')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        document = Document.objects.filter(pk=self.object.pk)
        document.update(download_count=F('download_count') + 1)
        return HttpResponseRedirect(self.object.get_download_url())


document_detail = DocumentDetailView.as_view()

templates/documents/_document_form.html
{% extends "forms/_base_modal.html" %}
{% load floppyforms %}


{% block headline %}
<div class="modal-icon" id="icon_document"></div><h2>ADD DOCUMENT</h2>
{% endblock %}


{% block fields %}
    {% form form using %}
        {% formconfig row using "forms/signup_row.html" %}

        {% formrow form.title %}
        {% formrow form.file %}
        {% formrow form.url %}
        {% formrow form.categories %}
        {% formrow form.tags %}
        {% formrow form.privacy %}
    {% endform %}
{% endblock %}

templates/documents/base.html
{% extends "base.html" %}
{% load thumbnail %}
{% load url from future %}


{% block content %}

    <div class="container">
        <div class="row">

            <div class="col-lg-12 hidden-xs">
                <ul class="nav nav-pills">
                <li class="active"><h2><a href="{% url "documents" %}">Reset</a></h2>
                {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                {% endfor %}
                </ul>
            </div>

        </div>
    </div>

    {% block pagecontent %}{% endblock %}

{% endblock %}

templates/documents/category_list.html
{% extends "base.html" %}
{% load djangular_tags thumbnail render_embeded %}

{% block content %}

<div id="content" class="clearfix">

  {% include "includes/topbar.html" %}

  <div class="container-fluid">

    <h3 class="withIcon icon_document"><span></span>ENGINE ROOM</h3>
    <a href="{% url "dashboard" %}" class="page-close"></a>

    {% include "documents/_document_form.html" with id="modal-form" form=form is_open=show_form %}

    <div class="row">

      <div class="col-md-12">
        <div class="row">
          <p class="margin-30-bottom">Choose a Category</p>
        </div>
        <ul id="engineRoomList" class="clearfix">
          {% for category in category_list %}
          <li>
            <a href="{{ category.get_absolute_url }}" class="detail">
              <h2>{{ category }}</h2>
              <p>{{ category.document_count }} File{{ category.document_count|pluralize:"s" }}</p>
              {% if category.latest_upload_date %}
              <p>Last updated {{ category.latest_upload_date|date }}</p>
              {% endif %}
              <p>Total Downloads {{ category.download_count }}</p>
            </a>
            <div class="feature">
                {% with category.list_image.object as object %}
                <img src="{{ object.file.url }}" alt="{{ object }}"/>
                {% endwith %}
            </div>
          </li>
          {% endfor %}
        </ul>

      </div>

    </div>


  </div>
</div>
<!-- CONTENT -->

{% endblock %}

templates/documents/document_detail.html
{% extends "base.html" %}
{% load djangular_tags webdesign thumbnail mediastore_tags markup_tags %}


{% block content %}
<div class="margin"></div>

<div id="objectsContainer" class="clearfix">

		<div class="detailObject">

			<div class="detailLeft">

			<h2 class="objectListTitle">{{ object.title }}</h2>
			{% comment %}<h4 class="newsdate">{{ object.pub_date|date:"j, F Y" }}</h4>{% endcomment %}

			<br/>

			<div class="editorLight">
    			<p>{{ object.article|safe }}</p>
    		</div>

			<br/>

			</div>


		</div>

	</div>

</div>
{% endblock %}

templates/documents/document_list.html
{% extends "base.html" %}
{% load floppyforms textformat %}

{% block content %}

<div id="content" class="clearfix">

	{% include "includes/topbar.html" %}

	<div class="container-fluid">

		<h3 class="withIcon icon_document"><span></span>THE ENGINE ROOM</h3>
        <a href="{% url "dashboard" %}" class="page-close"></a>

        <button class="btn btn-default action_addNew" data-target="#modal-form"{% if show_form %} data-open{% endif %}>ADD NEW DOCUMENT</button>

        {% include "documents/_document_form.html" with id="modal-form" form=form %}

        {{ category.description|textformat }}

		<div class="row">
			<div class="col-md-12">
				<br>
				<form class="form-inline instant-submit" role="form">
                {% form search_form using %}
                    {% formconfig row using "forms/signup_row.html" %}
					<div class="form-group">
						<label for="id_region">Filter by area</label>
                        {% formfield form.region %}
					</div>
					<div class="form-group">
						<label for="id_category">Filter by type</label>
                        {% formfield form.category %}
					</div>
                {% endform %}
				</form>

				<br>
                {% if document_list %}
                    <table class="table table-striped">
                        <thead>
                            <th>Title</th>
                            <th>Added by</th>
                            <th>Date added</th>
                            <th>File type</th>
                            <th>Size</th>
                            <th>Downloads</th>
                        </thead>
                        <tbody>
                        {% for document in document_list %}
                            <tr>
                                <td><a href="{{ document.get_absolute_url }}">{{ document.title }}</a></td>
                                <td>{{ document.local_mind }}</td>
                                <td>{{ document.created|date:"d/m/Y" }}</td>
                                <td>{% if document.file_type %}{{ document.file_type|upper }}{% endif %}</td>
                                <td>{% if document.file %}{{ document.file.size|filesizeformat }}{% endif %}</td>
                                <td>{{ document.download_count }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
			</div>
		</div>

	</div>

</div> <!-- CONTENT -->

{% endblock %}